// Ki Shogi - i18n
let lang = (Intl.DateTimeFormat().resolvedOptions().locale || '').startsWith('zh') ? 'zh' : 'en';

const S = {
  zh: {
    game_title: '麒将棋 Ki Shogi',
    lang_hint: 'L:语言/Lang',
    // Menu
    choose_opponent: '选择对手:',
    local_2p: '本地双人',
    ai_battle: 'AI 对战',
    tutorial: '规则教程',
    press_123: '按 1, 2 或 3 选择  ESC:返回  L:语言/Lang',
    choose_pieces: '选择棋子:',
    basic_set: '基础版 (玉+飛+角)',
    full_set: '完整版 (玉+飛+角+麒)',
    press_12: '按 1 或 2 选择  ESC:返回  L:语言/Lang',
    choose_diff: '选择难度:',
    diff_easy: '简单 (随机走棋)',
    diff_medium: '普通 (优先吃子/将军)',
    diff_hard: '困难 (会评估局面)',
    choose_side: '选择先后手:',
    play_black: '执黑 (先手)',
    play_white: '执白 (后手)',
    random: '随机',
    ai_vs_ai: 'AI 对战 AI',
    press_1234: '按 1, 2, 3 或 4 选择  ESC:返回  L:语言/Lang',
    // Game
    black: '黒 Black',
    white: '白 White',
    black_short: '黒',
    white_short: '白',
    wins: '胜利!',
    quit_menu: 'Q 退出  M 主菜单  R 重新开始',
    black_hand: '黒 持驹',
    white_hand: '白 持驹',
    hand_empty: '(空)',
    place_gyoku: '放置玉',
    place_gyoku_w: '放置玉',
    ai_thinking: 'AI 思考中...',
    your_turn: '的回合',
    controls_setup_1: '方向键:移动 Enter:确认',
    controls_setup_2: 'L:语言/Lang M:菜单 R:重开 Q:退出',
    controls_board_1: '方向键:移动 Enter:选中 D:放置持驹 Tab:棋谱',
    controls_board_2: 'L:语言/Lang M:菜单 R:重开 Q:退出',
    select_target: '选择目标',
    controls_move: '方向键:移动 Enter:确认 ESC:取消 L:语言/Lang',
    check: '将军!',
    choose_drop: '选择要放置的棋子:',
    controls_list: '↑↓:选择 Enter:确认 ESC:取消 L:语言/Lang',
    choose_face: '选择朝上的面:',
    choose_drop_pos: '选择放置位置 (绿色高亮):',
    controls_drop: '方向键:移动光标 Enter:确认 ESC:取消 L:语言/Lang',
    choose_promote: '选择升级面:',
    controls_promote: '↑↓:选择 Enter:确认 L:语言/Lang',
    // Hints
    hint_flip: '翻→',
    hint_promote: '吃升→',
    // Messages
    game_start: '对局开始!',
    invalid_pos: '无效位置，需距离黑玉恰好2格',
    no_hand: '没有持驹可放置',
    no_moves_check: '该棋子无法解除将军',
    no_moves: '该棋子无合法走法',
    not_yours: '不是你的棋子',
    empty_sq: '空格',
    invalid_target: '无效目标',
    cant_drop: '无法放置此棋子',
    no_drop_pos: '该面无合法放置位置',
    invalid_drop: '无效放置位置',
    place_black_gyoku: '黒方放置玉',
    log_title: '棋谱',
    log_browse_nav: '浏览',
    log_browse_back: '返回',
    draw: '和棋!',
    sennichite: '千日手 (局面重复四次)',
    sennichite_warning: '⚠ 局面已重复三次!',
    perpetual_check_lose: '反复将军判负',
    perpetual_check_warning: '⚠ 连续将军中，再重复将判负!',
    paused: '已暂停',
    space_pause: 'Space:暂停/继续',
    // Tutorial nav
    tut_title: '规则教程',
    tut_prev: '←上一页',
    tut_next: '→下一页',
    tut_back: 'ESC返回菜单',
  },
  en: {
    game_title: '麒将棋 Ki Shogi',
    lang_hint: 'L:语言/Lang',
    choose_opponent: 'Choose opponent:',
    local_2p: 'Local 2P',
    ai_battle: 'AI Battle',
    tutorial: 'Tutorial',
    press_123: 'Press 1, 2 or 3  ESC:Back  L:语言/Lang',
    choose_pieces: 'Choose pieces:',
    basic_set: 'Basic (玉+飛+角)',
    full_set: 'Full (玉+飛+角+麒)',
    press_12: 'Press 1 or 2  ESC:Back  L:语言/Lang',
    choose_diff: 'Difficulty:',
    diff_easy: 'Easy (random)',
    diff_medium: 'Normal (captures/checks)',
    diff_hard: 'Hard (evaluates board)',
    choose_side: 'Choose side:',
    play_black: 'Play Black (first)',
    play_white: 'Play White (second)',
    random: 'Random',
    ai_vs_ai: 'AI vs AI',
    press_1234: 'Press 1, 2, 3 or 4  ESC:Back  L:语言/Lang',
    black: '黒 Black',
    white: '白 White',
    black_short: '黒',
    white_short: '白',
    wins: 'Wins!',
    quit_menu: 'Q Quit  M Menu  R Restart',
    black_hand: '黒 Hand',
    white_hand: '白 Hand',
    hand_empty: '(none)',
    place_gyoku: 'Place 玉',
    place_gyoku_w: 'Place 玉',
    ai_thinking: 'AI thinking...',
    your_turn: "'s turn",
    controls_setup_1: 'Arrows:Move Enter:Confirm',
    controls_setup_2: 'L:语言/Lang M:Menu R:Restart Q:Quit',
    controls_board_1: 'Arrows:Move Enter:Select D:Drop Tab:Log',
    controls_board_2: 'L:语言/Lang M:Menu R:Restart Q:Quit',
    select_target: 'Select target',
    controls_move: 'Arrows:Move Enter:Confirm ESC:Cancel L:语言/Lang',
    check: 'Check!',
    choose_drop: 'Choose piece to drop:',
    controls_list: '↑↓:Choose Enter:OK ESC:Cancel L:语言/Lang',
    choose_face: 'Choose face up:',
    choose_drop_pos: 'Choose drop position (green):',
    controls_drop: 'Arrows:Move Enter:Confirm ESC:Cancel L:语言/Lang',
    choose_promote: 'Choose promotion:',
    controls_promote: '↑↓:Choose Enter:OK L:语言/Lang',
    hint_flip: 'Flip→',
    hint_promote: 'Cap→',
    game_start: 'Game start!',
    invalid_pos: 'Invalid: must be distance 2 from Black 玉',
    no_hand: 'No pieces to drop',
    no_moves_check: 'Cannot resolve check',
    no_moves: 'No legal moves',
    not_yours: 'Not your piece',
    empty_sq: 'Empty',
    invalid_target: 'Invalid target',
    cant_drop: 'Cannot drop this piece',
    no_drop_pos: 'No legal drop positions',
    invalid_drop: 'Invalid drop position',
    place_black_gyoku: 'Black places 玉',
    log_title: 'Log',
    log_browse_nav: 'Browse',
    log_browse_back: 'Back',
    draw: 'Draw!',
    sennichite: 'Sennichite (4-fold repetition)',
    sennichite_warning: '⚠ Position repeated 3 times!',
    perpetual_check_lose: 'Perpetual check — loses',
    perpetual_check_warning: '⚠ Perpetual check — one more repeats and you lose!',
    paused: 'Paused',
    space_pause: 'Space:Pause/Resume',
    tut_title: 'Tutorial',
    tut_prev: '←Prev',
    tut_next: 'Next→',
    tut_back: 'ESC:Back',
  },
};

function t(key) { return S[lang][key] || S.zh[key] || key; }
function toggleLang() { lang = lang === 'zh' ? 'en' : 'zh'; }
function getLang() { return lang; }

function getTutorialPages(A) {
  const { BOLD, RESET, FG_GRAY, FG_WHITE, FG_CYAN, FG_GREEN, FG_YELLOW, FG_RED } = A;
  if (lang === 'en') return _enTutorial(A);
  return _zhTutorial(A);
}

function _zhTutorial(A) {
  const { BOLD, RESET, FG_GRAY, FG_WHITE, FG_CYAN, FG_GREEN, FG_YELLOW, FG_RED } = A;
  return [
    [ '概述',
      '麒将棋是由 L.Lynn Smith 设计的，在无限棋盘上进行的两人对弈游戏。',
      '每方拥有骰子形状的棋子，每个面代表不同兵种。',
      '',
      `  ${FG_GRAY}. . . . . ${RESET} ${FG_WHITE}${BOLD}白色${RESET}${FG_GRAY}=黒方(先手)${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}玉${RESET}${FG_GRAY}. . . ${RESET} ${FG_CYAN}${BOLD}青色${RESET}${FG_GRAY}=白方(后手)${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}飛${FG_CYAN}${BOLD}角${FG_GRAY}. . ${RESET}`,
      `  ${FG_GRAY}. . . ${FG_CYAN}${BOLD}玉${FG_GRAY}. ${RESET}`,
      `  ${FG_GRAY}. . . . . ${RESET}`,
      '',
      '基础版: 玉 + 飛(飞车骰) + 角(角行骰)',
      '完整版: 额外加入 麒(麒麟骰)',
    ],
    [ '开局放置',
      '双方先放置自己的玉(王)。',
      '两个玉之间的切比雪夫距离必须恰好为2。',
      '',
      `  ${FG_GRAY}距离2的合法位置示例:${RESET}`,
      `  ${FG_GREEN}+ + + + + ${RESET}`,
      `  ${FG_GREEN}+ ${FG_GRAY}. . . ${FG_GREEN}+ ${RESET}`,
      `  ${FG_GREEN}+ ${FG_GRAY}. ${FG_WHITE}${BOLD}玉${RESET}${FG_GRAY}. ${FG_GREEN}+ ${RESET}`,
      `  ${FG_GREEN}+ ${FG_GRAY}. . . ${FG_GREEN}+ ${RESET}`,
      `  ${FG_GREEN}+ + + + + ${RESET}`,
      '',
      '放置完成后，其余棋子作为持驹，',
      '可在之后的回合中放置到棋盘上。',
    ],
    [ '移动与翻面',
      '每回合可以移动一个棋盘上的棋子。',
      '棋子按当前朝上面的走法移动。',
      '',
      `  ${FG_GRAY}不吃子移动 → 自动翻到对面:${RESET}`,
      `  ${FG_WHITE}${BOLD}飛${RESET}${FG_GRAY}(十字滑行)  移动后变  ${FG_WHITE}${BOLD}猪${RESET}${FG_GRAY}(十字一步)${RESET}`,
      '',
      `  ${FG_GRAY}移动前:     移动后:${RESET}`,
      `  ${FG_GRAY}. ${FG_CYAN}${BOLD}玉${FG_GRAY}.    . ${FG_CYAN}${BOLD}玉${FG_GRAY}. ${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}飛${FG_GRAY}. →  . . ${FG_WHITE}${BOLD}猪${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}玉${FG_GRAY}.    . ${FG_WHITE}${BOLD}玉${FG_GRAY}. ${RESET}`,
      '',
      '走法提示会显示在棋盘右侧。',
    ],
    [ '吃子与升级',
      '移动到对方棋子的位置即可吃掉它。',
      '',
      `  ${FG_GRAY}吃子前:     吃子后(选升级面):${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}飛${FG_CYAN}${BOLD}角${FG_GRAY}   . . ${FG_WHITE}${BOLD}仲${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}玉${FG_GRAY}. →  . ${FG_WHITE}${BOLD}玉${FG_GRAY}. ${RESET}`,
      '',
      '吃子后: 不翻面，而是选择一个升级面。',
      '  飛吃子后可升级为: 仲',
      '  被吃的棋子归入你的持驹。',
      '',
      '可以牺牲自己(悬空被吃)去吃麒方块。',
    ],
    [ '支撑规则',
      '棋子必须有支撑才能留在棋盘上:',
      '',
      `  ${FG_GRAY}普通棋子: 与玉或麒相邻(距离1)${RESET}`,
      `  ${FG_GRAY}麒方块: 距离玉1~2格，或与另外的麒相邻${RESET}`,
      '',
      `  ${FG_GREEN}+ + + + + ${FG_GRAY}. ${RESET}`,
      `  ${FG_GREEN}+ ${FG_WHITE}${BOLD}玉${FG_GREEN}+ ${FG_WHITE}${BOLD}麒飛${FG_GRAY}. ${RESET}${FG_GRAY} ←飛被麒支撑${RESET}`,
      `  ${FG_GREEN}+ + + + + ${FG_GRAY}. ${RESET}`,
      '',
      `  ${FG_GRAY}麒→麒可链式传递，扩展支撑范围。${RESET}`,
      '在己方回合结束时失去支撑的棋子会被对方俘获。',
    ],
    [ '放置持驹',
      '按 D 键进入放置模式。',
      '选择一个持驹 → 选择朝上的面 → 选择位置。',
      '',
      `  ${FG_GREEN}+ ${RESET}${FG_GRAY}=普通放置 ${FG_YELLOW}+ ${RESET}${FG_GRAY}=麒额外范围 ${FG_RED}x ${RESET}${FG_GRAY}=禁区${RESET}`,
      `  ${FG_YELLOW}+ + + + + ${FG_GRAY}. . ${RESET}`,
      `  ${FG_YELLOW}+ ${FG_GREEN}+ + ${FG_RED}x x x ${FG_GRAY}. ${RESET}`,
      `  ${FG_YELLOW}+ ${FG_GREEN}+ ${FG_WHITE}${BOLD}玉${FG_RED}x ${FG_CYAN}${BOLD}玉${FG_RED}x ${FG_GRAY}. ${RESET}${FG_GRAY} x=对方玉旁${RESET}`,
      `  ${FG_YELLOW}+ ${FG_GREEN}+ + ${FG_RED}x x x ${FG_GRAY}. ${RESET}`,
      `  ${FG_YELLOW}+ + + + + ${FG_GRAY}. . ${RESET}`,
      '',
      '普通棋子放在己方玉旁(距离1)。',
      '麒方块可放在距离己方玉1~2格内。',
      '额外限制: 不能通过放置将军。',
    ],
    [ '胜利条件',
      '吃掉对方的玉 → 立即获胜',
      '对方无合法行动 → 你获胜',
      '',
      `  ${FG_GRAY}将军示例: 飛威胁到白玉${RESET}`,
      `  ${FG_GRAY}. ${FG_CYAN}${BOLD}玉${FG_GRAY}. ${RESET}`,
      `  ${FG_GRAY}. ${FG_RED}||${FG_GRAY}. ${RESET}${FG_GRAY} ←飛的攻击线${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}飛${FG_GRAY}. ${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}玉${FG_GRAY}. ${RESET}`,
      '',
      '将军时对方必须解除，否则下回合玉被吃。',
      '',
      `  ${FG_YELLOW}祝你游戏愉快!${RESET}`,
    ],
  ];
}

function _enTutorial(A) {
  const { BOLD, RESET, FG_GRAY, FG_WHITE, FG_CYAN, FG_GREEN, FG_YELLOW, FG_RED } = A;
  return [
    [ 'Overview',
      'Ki Shogi is a two-player game on an infinite board, designed by L.Lynn Smith.',
      'Each side has dice-shaped pieces; each face is a different unit.',
      '',
      `  ${FG_GRAY}. . . . . ${RESET} ${FG_WHITE}${BOLD}White${RESET}${FG_GRAY}=Black (first)${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}玉${RESET}${FG_GRAY}. . . ${RESET} ${FG_CYAN}${BOLD}Cyan${RESET}${FG_GRAY}=White (second)${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}飛${FG_CYAN}${BOLD}角${FG_GRAY}. . ${RESET}`,
      `  ${FG_GRAY}. . . ${FG_CYAN}${BOLD}玉${FG_GRAY}. ${RESET}`,
      `  ${FG_GRAY}. . . . . ${RESET}`,
      '',
      'Basic: 玉 + 飛(Rook die) + 角(Bishop die)',
      'Full: adds 麒(Kirin die)',
    ],
    [ 'Setup',
      'Both sides place their 玉(King) first.',
      'The two 玉 must be exactly Chebyshev distance 2 apart.',
      '',
      `  ${FG_GRAY}Legal positions at distance 2:${RESET}`,
      `  ${FG_GREEN}+ + + + + ${RESET}`,
      `  ${FG_GREEN}+ ${FG_GRAY}. . . ${FG_GREEN}+ ${RESET}`,
      `  ${FG_GREEN}+ ${FG_GRAY}. ${FG_WHITE}${BOLD}玉${RESET}${FG_GRAY}. ${FG_GREEN}+ ${RESET}`,
      `  ${FG_GREEN}+ ${FG_GRAY}. . . ${FG_GREEN}+ ${RESET}`,
      `  ${FG_GREEN}+ + + + + ${RESET}`,
      '',
      'After placement, remaining pieces go to hand',
      'and can be dropped on later turns.',
    ],
    [ 'Movement & Flip',
      'Each turn you move one piece on the board.',
      'The piece moves according to its current face.',
      '',
      `  ${FG_GRAY}Non-capture move → auto-flip to opposite:${RESET}`,
      `  ${FG_WHITE}${BOLD}飛${RESET}${FG_GRAY}(cross slide) after move ${FG_WHITE}${BOLD}猪${RESET}${FG_GRAY}(cross step)${RESET}`,
      '',
      `  ${FG_GRAY}Before:     After:${RESET}`,
      `  ${FG_GRAY}. ${FG_CYAN}${BOLD}玉${FG_GRAY}.    . ${FG_CYAN}${BOLD}玉${FG_GRAY}. ${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}飛${FG_GRAY}. →  . . ${FG_WHITE}${BOLD}猪${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}玉${FG_GRAY}.    . ${FG_WHITE}${BOLD}玉${FG_GRAY}. ${RESET}`,
      '',
      'Move hints are shown to the right of the board.',
    ],
    [ 'Capture & Promote',
      'Move onto an opponent piece to capture it.',
      '',
      `  ${FG_GRAY}Before:     After (choose promotion):${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}飛${FG_CYAN}${BOLD}角${FG_GRAY}   . . ${FG_WHITE}${BOLD}仲${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}玉${FG_GRAY}. →  . ${FG_WHITE}${BOLD}玉${FG_GRAY}. ${RESET}`,
      '',
      'After capture: choose a promotion face (no flip).',
      '  飛 promotes to: 仲',
      '  Captured piece goes to your hand.',
      '',
      'You can sacrifice (strand) pieces to capture 麒 cubes.',
    ],
    [ 'Support Rule',
      'Pieces must be supported to stay on the board:',
      '',
      `  ${FG_GRAY}Normal pieces: adjacent to 玉 or 麒 (dist 1)${RESET}`,
      `  ${FG_GRAY}麒 cube: dist 1-2 from 玉, or adjacent to another 麒${RESET}`,
      '',
      `  ${FG_GREEN}+ + + + + ${FG_GRAY}. ${RESET}`,
      `  ${FG_GREEN}+ ${FG_WHITE}${BOLD}玉${FG_GREEN}+ ${FG_WHITE}${BOLD}麒飛${FG_GRAY}. ${RESET}${FG_GRAY} ←飛 supported by 麒${RESET}`,
      `  ${FG_GREEN}+ + + + + ${FG_GRAY}. ${RESET}`,
      '',
      `  ${FG_GRAY}麒→麒 chains extend support range.${RESET}`,
      'Unsupported pieces at end of turn are captured by opponent.',
    ],
    [ 'Dropping Pieces',
      'Press D to enter drop mode.',
      'Choose a hand piece → choose face → choose position.',
      '',
      `  ${FG_GREEN}+ ${RESET}${FG_GRAY}=normal drop ${FG_YELLOW}+ ${RESET}${FG_GRAY}=麒 extra range ${FG_RED}x ${RESET}${FG_GRAY}=forbidden${RESET}`,
      `  ${FG_YELLOW}+ + + + + ${FG_GRAY}. . ${RESET}`,
      `  ${FG_YELLOW}+ ${FG_GREEN}+ + ${FG_RED}x x x ${FG_GRAY}. ${RESET}`,
      `  ${FG_YELLOW}+ ${FG_GREEN}+ ${FG_WHITE}${BOLD}玉${FG_RED}x ${FG_CYAN}${BOLD}玉${FG_RED}x ${FG_GRAY}. ${RESET}${FG_GRAY} x=near opp 玉${RESET}`,
      `  ${FG_YELLOW}+ ${FG_GREEN}+ + ${FG_RED}x x x ${FG_GRAY}. ${RESET}`,
      `  ${FG_YELLOW}+ + + + + ${FG_GRAY}. . ${RESET}`,
      '',
      'Normal pieces drop adjacent to own 玉 (dist 1).',
      '麒 cube can drop at dist 1-2 from own 玉.',
      'Restriction: cannot give check by dropping.',
    ],
    [ 'Win Condition',
      'Capture opponent 玉 → instant win',
      'Opponent has no legal action → you win',
      '',
      `  ${FG_GRAY}Check example: 飛 threatens White 玉${RESET}`,
      `  ${FG_GRAY}. ${FG_CYAN}${BOLD}玉${FG_GRAY}. ${RESET}`,
      `  ${FG_GRAY}. ${FG_RED}||${FG_GRAY}. ${RESET}${FG_GRAY} ←飛 attack line${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}飛${FG_GRAY}. ${RESET}`,
      `  ${FG_GRAY}. ${FG_WHITE}${BOLD}玉${FG_GRAY}. ${RESET}`,
      '',
      'When in check, you must resolve it or 玉 is captured.',
      '',
      `  ${FG_YELLOW}Enjoy the game!${RESET}`,
    ],
  ];
}

module.exports = { t, toggleLang, getLang, getTutorialPages };
