// Ki Shogi - i18n

use std::sync::atomic::{AtomicU8, Ordering};

static LANG: AtomicU8 = AtomicU8::new(0); // 0 = En, 1 = Zh

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Lang { En, Zh }

pub fn get_lang() -> Lang {
    if LANG.load(Ordering::Relaxed) == 1 { Lang::Zh } else { Lang::En }
}

pub fn toggle_lang() {
    let cur = LANG.load(Ordering::Relaxed);
    LANG.store(if cur == 0 { 1 } else { 0 }, Ordering::Relaxed);
}

pub fn t(key: &str) -> &'static str {
    match get_lang() {
        Lang::Zh => t_zh(key),
        Lang::En => t_en(key),
    }
}

/// ANSI codes struct for tutorial pages
pub struct Ansi {
    pub bold: &'static str,
    pub reset: &'static str,
    pub fg_gray: &'static str,
    pub fg_white: &'static str,
    pub fg_cyan: &'static str,
    pub fg_green: &'static str,
    pub fg_yellow: &'static str,
    pub fg_red: &'static str,
}

pub fn get_tutorial_pages(a: &Ansi) -> Vec<Vec<String>> {
    match get_lang() {
        Lang::Zh => tutorial_zh(a),
        Lang::En => tutorial_en(a),
    }
}

fn tutorial_zh(a: &Ansi) -> Vec<Vec<String>> {
    let (b, r, gy, w, c, g, y, rd) = (a.bold, a.reset, a.fg_gray, a.fg_white, a.fg_cyan, a.fg_green, a.fg_yellow, a.fg_red);
    vec![
        vec![
            "概述".into(),
            "麒将棋是由 L.Lynn Smith 设计的，在无限棋盘上进行的两人对弈游戏。".into(),
            "每方拥有骰子形状的棋子，每个面代表不同兵种。".into(),
            String::new(),
            format!("  {gy}. . . . . {r} {w}{b}白色{r}{gy}=黒方(先手){r}"),
            format!("  {gy}. {w}{b}玉{r}{gy}. . . {r} {c}{b}青色{r}{gy}=白方(后手){r}"),
            format!("  {gy}. {w}{b}飛{c}{b}角{gy}. . {r}"),
            format!("  {gy}. . . {c}{b}玉{gy}. {r}"),
            format!("  {gy}. . . . . {r}"),
            String::new(),
            "基础版: 玉 + 飛(飞车骰) + 角(角行骰)".into(),
            "完整版: 额外加入 麒(麒麟骰)".into(),
        ],
        vec![
            "开局放置".into(),
            "双方先放置自己的玉(王)。".into(),
            "两个玉之间的切比雪夫距离必须恰好为2。".into(),
            String::new(),
            format!("  {gy}距离2的合法位置示例:{r}"),
            format!("  {g}+ + + + + {r}"),
            format!("  {g}+ {gy}. . . {g}+ {r}"),
            format!("  {g}+ {gy}. {w}{b}玉{r}{gy}. {g}+ {r}"),
            format!("  {g}+ {gy}. . . {g}+ {r}"),
            format!("  {g}+ + + + + {r}"),
            String::new(),
            "放置完成后，其余棋子作为持驹，".into(),
            "可在之后的回合中放置到棋盘上。".into(),
        ],
        vec![
            "移动与翻面".into(),
            "每回合可以移动一个棋盘上的棋子。".into(),
            "棋子按当前朝上面的走法移动。".into(),
            String::new(),
            format!("  {gy}不吃子移动 → 自动翻到对面:{r}"),
            format!("  {w}{b}飛{r}{gy}(十字滑行)  移动后变  {w}{b}猪{r}{gy}(十字一步){r}"),
            String::new(),
            format!("  {gy}移动前:     移动后:{r}"),
            format!("  {gy}. {c}{b}玉{gy}.    . {c}{b}玉{gy}. {r}"),
            format!("  {gy}. {w}{b}飛{gy}. →  . . {w}{b}猪{r}"),
            format!("  {gy}. {w}{b}玉{gy}.    . {w}{b}玉{gy}. {r}"),
            String::new(),
            "走法提示会显示在棋盘右侧。".into(),
        ],
        vec![
            "吃子与升级".into(),
            "移动到对方棋子的位置即可吃掉它。".into(),
            String::new(),
            format!("  {gy}吃子前:     吃子后(选升级面):{r}"),
            format!("  {gy}. {w}{b}飛{c}{b}角{gy}   . . {w}{b}仲{r}"),
            format!("  {gy}. {w}{b}玉{gy}. →  . {w}{b}玉{gy}. {r}"),
            String::new(),
            "吃子后: 不翻面，而是选择一个升级面。".into(),
            "  飛吃子后可升级为: 仲".into(),
            "  被吃的棋子归入你的持驹。".into(),
            String::new(),
            "可以牺牲自己(悬空被吃)去吃麒方块。".into(),
        ],
        vec![
            "支撑规则".into(),
            "棋子必须有支撑才能留在棋盘上:".into(),
            String::new(),
            format!("  {gy}普通棋子: 与玉或麒相邻(距离1){r}"),
            format!("  {gy}麒方块: 距离玉1~2格，或与另外的麒相邻{r}"),
            String::new(),
            format!("  {g}+ + + + + {gy}. {r}"),
            format!("  {g}+ {w}{b}玉{g}+ {w}{b}麒飛{gy}. {r}{gy} ←飛被麒支撑{r}"),
            format!("  {g}+ + + + + {gy}. {r}"),
            String::new(),
            format!("  {gy}麒→麒可链式传递，扩展支撑范围。{r}"),
            "在己方回合结束时失去支撑的棋子会被对方俘获。".into(),
        ],
        vec![
            "放置持驹".into(),
            "按 D 键进入放置模式。".into(),
            "选择一个持驹 → 选择朝上的面 → 选择位置。".into(),
            String::new(),
            format!("  {g}+ {r}{gy}=普通放置 {y}+ {r}{gy}=麒额外范围 {rd}x {r}{gy}=禁区{r}"),
            format!("  {y}+ + + + + {gy}. . {r}"),
            format!("  {y}+ {g}+ + {rd}x x x {gy}. {r}"),
            format!("  {y}+ {g}+ {w}{b}玉{rd}x {c}{b}玉{rd}x {gy}. {r}{gy} x=对方玉旁{r}"),
            format!("  {y}+ {g}+ + {rd}x x x {gy}. {r}"),
            format!("  {y}+ + + + + {gy}. . {r}"),
            String::new(),
            "普通棋子放在己方玉旁(距离1)。".into(),
            "麒方块可放在距离己方玉1~2格内。".into(),
            "额外限制: 不能通过放置将军。".into(),
        ],
        vec![
            "胜利条件".into(),
            "吃掉对方的玉 → 立即获胜".into(),
            "对方无合法行动 → 你获胜".into(),
            String::new(),
            format!("  {gy}将军示例: 飛威胁到白玉{r}"),
            format!("  {gy}. {c}{b}玉{gy}. {r}"),
            format!("  {gy}. {rd}||{gy}. {r}{gy} ←飛的攻击线{r}"),
            format!("  {gy}. {w}{b}飛{gy}. {r}"),
            format!("  {gy}. {w}{b}玉{gy}. {r}"),
            String::new(),
            "将军时对方必须解除，否则下回合玉被吃。".into(),
            String::new(),
            format!("  {y}祝你游戏愉快!{r}"),
        ],
    ]
}

fn tutorial_en(a: &Ansi) -> Vec<Vec<String>> {
    let (b, r, gy, w, c, g, y, rd) = (a.bold, a.reset, a.fg_gray, a.fg_white, a.fg_cyan, a.fg_green, a.fg_yellow, a.fg_red);
    vec![
        vec![
            "Overview".into(),
            "Ki Shogi is a two-player game on an infinite board, designed by L.Lynn Smith.".into(),
            "Each side has dice-shaped pieces; each face is a different unit.".into(),
            String::new(),
            format!("  {gy}. . . . . {r} {w}{b}White{r}{gy}=Black (first){r}"),
            format!("  {gy}. {w}{b}玉{r}{gy}. . . {r} {c}{b}Cyan{r}{gy}=White (second){r}"),
            format!("  {gy}. {w}{b}飛{c}{b}角{gy}. . {r}"),
            format!("  {gy}. . . {c}{b}玉{gy}. {r}"),
            format!("  {gy}. . . . . {r}"),
            String::new(),
            "Basic: 玉 + 飛(Rook die) + 角(Bishop die)".into(),
            "Full: adds 麒(Kirin die)".into(),
        ],
        vec![
            "Setup".into(),
            "Both sides place their 玉(King) first.".into(),
            "The two 玉 must be exactly Chebyshev distance 2 apart.".into(),
            String::new(),
            format!("  {gy}Legal positions at distance 2:{r}"),
            format!("  {g}+ + + + + {r}"),
            format!("  {g}+ {gy}. . . {g}+ {r}"),
            format!("  {g}+ {gy}. {w}{b}玉{r}{gy}. {g}+ {r}"),
            format!("  {g}+ {gy}. . . {g}+ {r}"),
            format!("  {g}+ + + + + {r}"),
            String::new(),
            "After placement, remaining pieces go to hand".into(),
            "and can be dropped on later turns.".into(),
        ],
        vec![
            "Movement & Flip".into(),
            "Each turn you move one piece on the board.".into(),
            "The piece moves according to its current face.".into(),
            String::new(),
            format!("  {gy}Non-capture move → auto-flip to opposite:{r}"),
            format!("  {w}{b}飛{r}{gy}(cross slide) after move {w}{b}猪{r}{gy}(cross step){r}"),
            String::new(),
            format!("  {gy}Before:     After:{r}"),
            format!("  {gy}. {c}{b}玉{gy}.    . {c}{b}玉{gy}. {r}"),
            format!("  {gy}. {w}{b}飛{gy}. →  . . {w}{b}猪{r}"),
            format!("  {gy}. {w}{b}玉{gy}.    . {w}{b}玉{gy}. {r}"),
            String::new(),
            "Move hints are shown to the right of the board.".into(),
        ],
        vec![
            "Capture & Promote".into(),
            "Move onto an opponent piece to capture it.".into(),
            String::new(),
            format!("  {gy}Before:     After (choose promotion):{r}"),
            format!("  {gy}. {w}{b}飛{c}{b}角{gy}   . . {w}{b}仲{r}"),
            format!("  {gy}. {w}{b}玉{gy}. →  . {w}{b}玉{gy}. {r}"),
            String::new(),
            "After capture: choose a promotion face (no flip).".into(),
            "  飛 promotes to: 仲".into(),
            "  Captured piece goes to your hand.".into(),
            String::new(),
            "You can sacrifice (strand) pieces to capture 麒 cubes.".into(),
        ],
        vec![
            "Support Rule".into(),
            "Pieces must be supported to stay on the board:".into(),
            String::new(),
            format!("  {gy}Normal pieces: adjacent to 玉 or 麒 (dist 1){r}"),
            format!("  {gy}麒 cube: dist 1-2 from 玉, or adjacent to another 麒{r}"),
            String::new(),
            format!("  {g}+ + + + + {gy}. {r}"),
            format!("  {g}+ {w}{b}玉{g}+ {w}{b}麒飛{gy}. {r}{gy} ←飛 supported by 麒{r}"),
            format!("  {g}+ + + + + {gy}. {r}"),
            String::new(),
            format!("  {gy}麒→麒 chains extend support range.{r}"),
            "Unsupported pieces at end of turn are captured by opponent.".into(),
        ],
        vec![
            "Dropping Pieces".into(),
            "Press D to enter drop mode.".into(),
            "Choose a hand piece → choose face → choose position.".into(),
            String::new(),
            format!("  {g}+ {r}{gy}=normal drop {y}+ {r}{gy}=麒 extra range {rd}x {r}{gy}=forbidden{r}"),
            format!("  {y}+ + + + + {gy}. . {r}"),
            format!("  {y}+ {g}+ + {rd}x x x {gy}. {r}"),
            format!("  {y}+ {g}+ {w}{b}玉{rd}x {c}{b}玉{rd}x {gy}. {r}{gy} x=near opp 玉{r}"),
            format!("  {y}+ {g}+ + {rd}x x x {gy}. {r}"),
            format!("  {y}+ + + + + {gy}. . {r}"),
            String::new(),
            "Normal pieces drop adjacent to own 玉 (dist 1).".into(),
            "麒 cube can drop at dist 1-2 from own 玉.".into(),
            "Restriction: cannot give check by dropping.".into(),
        ],
        vec![
            "Win Condition".into(),
            "Capture opponent 玉 → instant win".into(),
            "Opponent has no legal action → you win".into(),
            String::new(),
            format!("  {gy}Check example: 飛 threatens White 玉{r}"),
            format!("  {gy}. {c}{b}玉{gy}. {r}"),
            format!("  {gy}. {rd}||{gy}. {r}{gy} ←飛 attack line{r}"),
            format!("  {gy}. {w}{b}飛{gy}. {r}"),
            format!("  {gy}. {w}{b}玉{gy}. {r}"),
            String::new(),
            "When in check, you must resolve it or 玉 is captured.".into(),
            String::new(),
            format!("  {y}Enjoy the game!{r}"),
        ],
    ]
}

fn t_zh(key: &str) -> &'static str {
    match key {
        "game_title" => "麒将棋 Ki Shogi",
        "lang_hint" => "L:语言/Lang",
        "choose_opponent" => "选择对手:",
        "local_2p" => "本地双人",
        "ai_battle" => "AI 对战",
        "tutorial" => "规则教程",
        "press_123" => "按 1, 2 或 3 选择  ESC:返回  L:语言/Lang",
        "choose_pieces" => "选择棋子:",
        "basic_set" => "基础版 (玉+飛+角)",
        "full_set" => "完整版 (玉+飛+角+麒)",
        "press_12" => "按 1 或 2 选择  ESC:返回  L:语言/Lang",
        "choose_diff" => "选择难度:",
        "diff_easy" => "入门 (随机走棋)",
        "diff_medium" => "简单 (优先吃子/将军)",
        "diff_hard" => "普通 (会评估局面)",
        "diff_very_hard" => "困难 (深度搜索)",
        "diff_extreme" => "地狱 (最深搜索)",
        "choose_side" => "选择先后手:",
        "play_black" => "执黑 (先手)",
        "play_white" => "执白 (后手)",
        "random" => "随机",
        "ai_vs_ai" => "AI 对战 AI",
        "press_1234" => "按 1, 2, 3 或 4 选择  ESC:返回  L:语言/Lang",
        "press_12345" => "按 1-5 选择  ESC:返回  L:语言/Lang",
        "black" => "黒 Black",
        "white" => "白 White",
        "black_short" => "黒",
        "white_short" => "白",
        "wins" => "胜利!",
        "quit_menu" => "Q 退出  M 主菜单  R 重新开始",
        "black_hand" => "黒 持驹",
        "white_hand" => "白 持驹",
        "hand_empty" => "(空)",
        "place_gyoku" => "放置玉",
        "place_gyoku_w" => "放置玉",
        "ai_thinking" => "AI 思考中...",
        "your_turn" => "的回合",
        "controls_setup_1" => "方向键:移动 Enter:确认",
        "controls_setup_2" => "L:语言/Lang M:菜单 R:重开 Q:退出",
        "controls_board_1" => "方向键:移动 Enter:选中 D:放置持驹 Tab:棋谱",
        "controls_board_2" => "L:语言/Lang M:菜单 R:重开 Q:退出",
        "select_target" => "选择目标",
        "controls_move" => "方向键:移动 Enter:确认 ESC:取消 L:语言/Lang",
        "check" => "将军!",
        "choose_drop" => "选择要放置的棋子:",
        "controls_list" => "↑↓:选择 Enter:确认 ESC:取消 L:语言/Lang",
        "choose_face" => "选择朝上的面:",
        "choose_drop_pos" => "选择放置位置 (绿色高亮):",
        "controls_drop" => "方向键:移动光标 Enter:确认 ESC:取消 L:语言/Lang",
        "choose_promote" => "选择升级面:",
        "controls_promote" => "↑↓:选择 Enter:确认 L:语言/Lang",
        "hint_flip" => "翻→",
        "hint_promote" => "吃升→",
        "game_start" => "对局开始!",
        "invalid_pos" => "无效位置，需距离黑玉恰好2格",
        "no_hand" => "没有持驹可放置",
        "no_moves_check" => "该棋子无法解除将军",
        "no_moves" => "该棋子无合法走法",
        "not_yours" => "不是你的棋子",
        "empty_sq" => "空格",
        "invalid_target" => "无效目标",
        "cant_drop" => "无法放置此棋子",
        "no_drop_pos" => "该面无合法放置位置",
        "invalid_drop" => "无效放置位置",
        "place_black_gyoku" => "黒方放置玉",
        "log_title" => "棋谱",
        "log_browse_nav" => "浏览",
        "log_browse_back" => "返回",
        "draw" => "和棋!",
        "sennichite" => "千日手 (局面重复四次)",
        "sennichite_warning" => "⚠ 局面已重复三次!",
        "perpetual_check_lose" => "反复将军判负",
        "perpetual_check_warning" => "⚠ 连续将军中，再重复将判负!",
        "paused" => "已暂停",
        "space_pause" => "Space:暂停/继续",
        "tut_title" => "规则教程",
        "tut_prev" => "←上一页",
        "tut_next" => "→下一页",
        "tut_back" => "ESC返回菜单",
        _ => t_en(key), // fallback
    }
}

fn t_en(key: &str) -> &'static str {
    match key {
        "game_title" => "麒将棋 Ki Shogi",
        "lang_hint" => "L:语言/Lang",
        "choose_opponent" => "Choose opponent:",
        "local_2p" => "Local 2P",
        "ai_battle" => "AI Battle",
        "tutorial" => "Tutorial",
        "press_123" => "Press 1, 2 or 3  ESC:Back  L:语言/Lang",
        "choose_pieces" => "Choose pieces:",
        "basic_set" => "Basic (玉+飛+角)",
        "full_set" => "Full (玉+飛+角+麒)",
        "press_12" => "Press 1 or 2  ESC:Back  L:语言/Lang",
        "choose_diff" => "Difficulty:",
        "diff_easy" => "Trivial (random)",
        "diff_medium" => "Easy (captures/checks)",
        "diff_hard" => "Medium (evaluates board)",
        "diff_very_hard" => "Hard (deep search)",
        "diff_extreme" => "Extreme (deepest search)",
        "choose_side" => "Choose side:",
        "play_black" => "Play Black (first)",
        "play_white" => "Play White (second)",
        "random" => "Random",
        "ai_vs_ai" => "AI vs AI",
        "press_1234" => "Press 1, 2, 3 or 4  ESC:Back  L:语言/Lang",
        "press_12345" => "Press 1-5  ESC:Back  L:语言/Lang",
        "black" => "黒 Black",
        "white" => "白 White",
        "black_short" => "黒",
        "white_short" => "白",
        "wins" => "Wins!",
        "quit_menu" => "Q Quit  M Menu  R Restart",
        "black_hand" => "黒 Hand",
        "white_hand" => "白 Hand",
        "hand_empty" => "(none)",
        "place_gyoku" => "Place 玉",
        "place_gyoku_w" => "Place 玉",
        "ai_thinking" => "AI thinking...",
        "your_turn" => "'s turn",
        "controls_setup_1" => "Arrows:Move Enter:Confirm",
        "controls_setup_2" => "L:语言/Lang M:Menu R:Restart Q:Quit",
        "controls_board_1" => "Arrows:Move Enter:Select D:Drop Tab:Log",
        "controls_board_2" => "L:语言/Lang M:Menu R:Restart Q:Quit",
        "select_target" => "Select target",
        "controls_move" => "Arrows:Move Enter:Confirm ESC:Cancel L:语言/Lang",
        "check" => "Check!",
        "choose_drop" => "Choose piece to drop:",
        "controls_list" => "↑↓:Choose Enter:OK ESC:Cancel L:语言/Lang",
        "choose_face" => "Choose face up:",
        "choose_drop_pos" => "Choose drop position (green):",
        "controls_drop" => "Arrows:Move Enter:Confirm ESC:Cancel L:语言/Lang",
        "choose_promote" => "Choose promotion:",
        "controls_promote" => "↑↓:Choose Enter:OK L:语言/Lang",
        "hint_flip" => "Flip→",
        "hint_promote" => "Cap→",
        "game_start" => "Game start!",
        "invalid_pos" => "Invalid: must be distance 2 from Black 玉",
        "no_hand" => "No pieces to drop",
        "no_moves_check" => "Cannot resolve check",
        "no_moves" => "No legal moves",
        "not_yours" => "Not your piece",
        "empty_sq" => "Empty",
        "invalid_target" => "Invalid target",
        "cant_drop" => "Cannot drop this piece",
        "no_drop_pos" => "No legal drop positions",
        "invalid_drop" => "Invalid drop position",
        "place_black_gyoku" => "Black places 玉",
        "log_title" => "Log",
        "log_browse_nav" => "Browse",
        "log_browse_back" => "Back",
        "draw" => "Draw!",
        "sennichite" => "Sennichite (4-fold repetition)",
        "sennichite_warning" => "⚠ Position repeated 3 times!",
        "perpetual_check_lose" => "Perpetual check — loses",
        "perpetual_check_warning" => "⚠ Perpetual check — one more repeats and you lose!",
        "paused" => "Paused",
        "space_pause" => "Space:Pause/Resume",
        "tut_title" => "Tutorial",
        "tut_prev" => "←Prev",
        "tut_next" => "Next→",
        "tut_back" => "ESC:Back",
        _ => "???",
    }
}
